### ISSUE TITLE
Read all entrys from table (pagination)

### ISSUE THREAD

**Issue by kpleines** [elchicodepython/python-nocodb#10]
Thanks for providing this projekt in python and the initial documentation.
If I send my "table_row_list", the return list only contains 25 rows of the table. Is there a parameter to fetch all rows at once or drill down to fetch the next 25 rows?
(client.table_row_list(project, table_name, InFilter("lager", lagerType)))

Thanks for answer.

**Comment by elchicodepython** [comment]
Hello @kpleines,

You can tweak the number of rows retrieved using the limit param. You have this info in the README. I'm sorry if it's not clear enough.

`table_rows = client.table_row_list(project, table_name, params={'limit': 10000})`

Also let see that you want to paginate them. You can combine limit+offset params to paginate the rows.

```python
first_100_rows = client.table_row_list(project, table_name, params={'limit': 100})
next_100_rows = client.table_row_list(project, table_name, params={'limit': 100, 'offset': 100})
next_100_rows = client.table_row_list(project, table_name, params={'limit': 100, 'offset': 200})
```

An automatic pagination could be great but unfortunately it doesn't exists at the moment . I'm adding an issue for this. It can be done with a python generator and It can be very funny to use :) 

Have a nice day! 😄

**Comment by kpleines** [comment]
Ok, thanks for the quick response. 
Have a nice day too.

**Comment by elchicodepython** [comment]
A comment related to this. The max limit seems to be 1000 rows. So if we specify a limit over 1000 it will return only the first 1000.
