### ISSUE TITLE
getting all rows from a table doesn't really work

### ISSUE THREAD

**Issue by alx-xlx** [elchicodepython/python-nocodb#15]
https://github.com/elchicodepython/python-nocodb/issues/10#issuecomment-1526309404

```
# Retrieve the first 10000 rows
table_rows = client.table_row_list(project, table_name, params={'limit': 10000})
```

I saw that the only first **1000** rows can be extracted at once and not **10000** as you say on readme
I have also attached this image showing the length of rows.
If you can fix that then it would be great, Thanks :)

![YeMn0RTZCg](https://github.com/elchicodepython/python-nocodb/assets/42188371/3272b8d2-453c-4bf4-b8dc-a0c4aaeb240a)

**Comment by elchicodepython** [comment]
Hello! Good catch. I'm updating the readme. You can get all the rows from a table [using pagination](https://github.com/elchicodepython/python-nocodb/issues/10).

**Comment by elchicodepython** [comment]
I updated the README @alx-xlx 

You can retrieve all the rows from a table using pagination 😊 . Example:

```
first_100_rows = client.table_row_list(project, table_name, params={'limit': 100})
next_100_rows = client.table_row_list(project, table_name, params={'limit': 100, 'offset': 100})
next_100_rows = client.table_row_list(project, table_name, params={'limit': 100, 'offset': 200})
```

Please tell me if you have any doubt about it 🙏🏻 .
