### ISSUE TITLE
whl is missing at pypi - pip install failed

### ISSUE THREAD

**Issue by johnatank** [elchicodepython/python-nocodb#16]
Hi,
Seems like whl file is missing for nocodb 2.0.0 and 2.0.1 at pypi.org. pip is skipping releases where egg file exists:
`
pip install nocodb==2.0.1 -vvv     
...
https://files.pythonhosted.org/packages/64/58/dbd52713b948b7c30ed4bdabd3b2b9655781e4dd581d89807cb5af379185/nocodb-1.0.0-py3-none-any.whl (from https://pypi.org/simple/nocodb/), version: 1.0.0
  Found link https://files.pythonhosted.org/packages/93/c2/fab4554f7d4206df5a776b48923d16c1e45167541e7b14a7f2ff8e3cfa76/nocodb-1.0.1-py3-none-any.whl (from https://pypi.org/simple/nocodb/), version: 1.0.1
  Found link https://files.pythonhosted.org/packages/fb/6b/1a7e04c3f128860396e4734fc569ad150608f7a8861099a4d21dbce79096/nocodb-2.0.0a1.tar.gz (from https://pypi.org/simple/nocodb/), version: 2.0.0a1
  Found link https://files.pythonhosted.org/packages/dd/2f/c72c42d254b085e59dc8900c0bf612ab1773d4ff52e55bcba030302bcd3c/nocodb-2.0.0a2-py3-none-any.whl (from https://pypi.org/simple/nocodb/), version: 2.0.0a2
  Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/37/0a/37e8450163537055fd93c42a081457b4892ce19baca6b402bea3938ef828/nocodb-2.0.0-py3.9.egg (from https://pypi.org/simple/nocodb/)
  Skipping link: unsupported archive format: .egg: https://files.pythonhosted.org/packages/31/53/088ee8cf35ec4e1831ec6f0851b5ab2aa7ba58d4ade3d68b1aa8bdde5ce8/nocodb-2.0.1-py3.9.egg (from https://pypi.org/simple/nocodb/)
Skipping link: not a file: https://pypi.org/simple/nocodb/
Given no hashes to check 0 links for project 'nocodb': discarding no candidates
ERROR: Could not find a version that satisfies the requirement nocodb==2.0.1 (from versions: 0.0.1, 0.0.2, 0.1.0, 1.0.0, 1.0.1, 2.0.0a1, 2.0.0a2)
ERROR: No matching distribution found for nocodb==2.0.1
...
`
Isn't egg - outdated? Can wheel format be added for pip to work properly?
Thanks.

**Comment by elchicodepython** [comment]
Thank you! Checking this

**Comment by elchicodepython** [comment]
Hello @johnatank! Thanks for the catch!

There were only alfa versions uploaded to pypi.

Added 2.0.0 and the 2.0.1 :)
