### ISSUE TITLE
New comparison and logical operators

### ISSUE THREAD

**Issue by MitPitt** [elchicodepython/python-nocodb#4]
There are more filters available now, as well as AND/OR/NOT logical operators. Would really appreciate it if you implemented them.
https://docs.nocodb.com/developer-resources/rest-apis/#comparison-operators
https://docs.nocodb.com/developer-resources/rest-apis/#logical-operators

**Comment by elchicodepython** [comment]
Hello @MitPitt!
Sorry for the late reply!
Seems good. I will take a look at them.

I add this enhancement to a new 0.2 milestone.

**Comment by elchicodepython** [comment]
I've started to work on adding more comparison operators in v2.0. I will make a back port without breaking changes to 0.2 when finished. In v2.0 I'm going to introduce a breaking change renaming `In` filter to `like`.

I've published an alpha for the moment so anyone can test it.

https://pypi.org/project/nocodb/2.0.0a1/

**Comment by elchicodepython** [comment]
Hello @MitPitt I released a new 2.0.0 version adding new operators :)
